name: BeansBeans
version: 0.4.3
api-version: 1.18
main: me.playground.main.Main
softdepend: [WorldEdit, dynmap, ProtocolLib]
author: Mogubean
website: https://beansbeans.net
description: The plugin home to every feature of Bean's Bean's.
commands: