name: BeansBeans
version: 0.4.4
api-version: 1.18
main: me.playground.main.Main
softdepend: [WorldEdit, dynmap, ProtocolLib]
author: Mogubean
website: http://beansbeans.net
description: The plugin home to every feature of Bean's Beans.
commands: