name: BeansBeans
version: 0.5.3
api-version: 1.19
main: me.playground.main.Main
softdepend: [WorldEdit, dynmap, ProtocolLib]
author: Mogubean
website: http://beansbeans.net
description: The plugin home to every feature of Bean's Beans.
commands: